# Site settings
title: BANACOLA

# Short bio or description (displayed in the header)
description: BANACOLA GAMES

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/16319467?v=3&s=460
keywords: BANACOLA

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME